---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: xfo-beta

description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 43 

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
  - type: dnf
    repos:
      cleanup: false
      files: 
        - https://repo.librewolf.net/librewolf.repo
      nonfree: negativo17
    install:
      packages:
        - librewolf
        - fastfetch
        - https://github.com/Vencord/Vesktop/releases/download/v1.6.5/vesktop-1.6.5.x86_64.rpm
        - steam
        - nvim
    remove:
      packages:
        - firefox
        - firefox-langpacks 
        - vim
        - nano
  - type: default-flatpaks
    configurations:
      - notify: false 
        scope: system
        install: # system flatpaks we want all users to have and not remove
          - org.vinegarhq.Sober
          - org.prismlauncher.PrismLauncher
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
